{{- if and (not .Values.secretRef) .Values.apiToken }}
apiVersion: v1
kind: Secret
metadata:
  name: linode-api-token
  namespace: {{ .Values.namespace }}
stringData:
  token: {{ .Values.apiToken }}
type: Opaque
{{- end }}
