{{- if and .Values.controller.enabled .Values.controller.serviceAccount.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.controller.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
{{- end }}
{{- if and .Values.controller.enabled .Values.controller.serviceAccount.enabled .Values.node.enabled .Values.node.serviceAccount.enabled }}
---
{{- end }}
{{- if and .Values.node.enabled .Values.node.serviceAccount.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.node.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
{{- end }}
