// Code generated by MockGen. DO NOT EDIT.
// Source: internal/driver/metadata.go
//
// Generated by this command:
//
//	mockgen -source=internal/driver/metadata.go -destination=mocks/mock_metadata.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	metadata "github.com/linode/go-metadata"
	gomock "go.uber.org/mock/gomock"
	v1 "k8s.io/api/core/v1"
)

// MockInstanceMetadataClient is a mock of InstanceMetadataClient interface.
type MockInstanceMetadataClient struct {
	ctrl     *gomock.Controller
	recorder *MockInstanceMetadataClientMockRecorder
	isgomock struct{}
}

// MockInstanceMetadataClientMockRecorder is the mock recorder for MockInstanceMetadataClient.
type MockInstanceMetadataClientMockRecorder struct {
	mock *MockInstanceMetadataClient
}

// NewMockInstanceMetadataClient creates a new mock instance.
func NewMockInstanceMetadataClient(ctrl *gomock.Controller) *MockInstanceMetadataClient {
	mock := &MockInstanceMetadataClient{ctrl: ctrl}
	mock.recorder = &MockInstanceMetadataClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInstanceMetadataClient) EXPECT() *MockInstanceMetadataClientMockRecorder {
	return m.recorder
}

// GetInstance mocks base method.
func (m *MockInstanceMetadataClient) GetInstance(ctx context.Context) (*metadata.InstanceData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInstance", ctx)
	ret0, _ := ret[0].(*metadata.InstanceData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInstance indicates an expected call of GetInstance.
func (mr *MockInstanceMetadataClientMockRecorder) GetInstance(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInstance", reflect.TypeOf((*MockInstanceMetadataClient)(nil).GetInstance), ctx)
}

// GetNetwork mocks base method.
func (m *MockInstanceMetadataClient) GetNetwork(ctx context.Context) (*metadata.NetworkData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNetwork", ctx)
	ret0, _ := ret[0].(*metadata.NetworkData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNetwork indicates an expected call of GetNetwork.
func (mr *MockInstanceMetadataClientMockRecorder) GetNetwork(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNetwork", reflect.TypeOf((*MockInstanceMetadataClient)(nil).GetNetwork), ctx)
}

// MockKubeNodeClient is a mock of KubeNodeClient interface.
type MockKubeNodeClient struct {
	ctrl     *gomock.Controller
	recorder *MockKubeNodeClientMockRecorder
	isgomock struct{}
}

// MockKubeNodeClientMockRecorder is the mock recorder for MockKubeNodeClient.
type MockKubeNodeClientMockRecorder struct {
	mock *MockKubeNodeClient
}

// NewMockKubeNodeClient creates a new mock instance.
func NewMockKubeNodeClient(ctrl *gomock.Controller) *MockKubeNodeClient {
	mock := &MockKubeNodeClient{ctrl: ctrl}
	mock.recorder = &MockKubeNodeClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKubeNodeClient) EXPECT() *MockKubeNodeClientMockRecorder {
	return m.recorder
}

// GetNode mocks base method.
func (m *MockKubeNodeClient) GetNode(ctx context.Context, name string) (*v1.Node, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNode", ctx, name)
	ret0, _ := ret[0].(*v1.Node)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNode indicates an expected call of GetNode.
func (mr *MockKubeNodeClientMockRecorder) GetNode(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNode", reflect.TypeOf((*MockKubeNodeClient)(nil).GetNode), ctx, name)
}

// ListNodes mocks base method.
func (m *MockKubeNodeClient) ListNodes(ctx context.Context) (*v1.NodeList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNodes", ctx)
	ret0, _ := ret[0].(*v1.NodeList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNodes indicates an expected call of ListNodes.
func (mr *MockKubeNodeClientMockRecorder) ListNodes(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNodes", reflect.TypeOf((*MockKubeNodeClient)(nil).ListNodes), ctx)
}
