// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/linode-client/client.go
//
// Generated by this command:
//
//	mockgen -source=pkg/linode-client/client.go -destination=mocks/mock_linodeclient.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	linodego "github.com/linode/linodego/v2"
	gomock "go.uber.org/mock/gomock"
)

// MockLinodeClient is a mock of LinodeClient interface.
type MockLinodeClient struct {
	ctrl     *gomock.Controller
	recorder *MockLinodeClientMockRecorder
	isgomock struct{}
}

// MockLinodeClientMockRecorder is the mock recorder for MockLinodeClient.
type MockLinodeClientMockRecorder struct {
	mock *MockLinodeClient
}

// NewMockLinodeClient creates a new mock instance.
func NewMockLinodeClient(ctrl *gomock.Controller) *MockLinodeClient {
	mock := &MockLinodeClient{ctrl: ctrl}
	mock.recorder = &MockLinodeClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinodeClient) EXPECT() *MockLinodeClientMockRecorder {
	return m.recorder
}

// CloneNFSSnapshot mocks base method.
func (m *MockLinodeClient) CloneNFSSnapshot(ctx context.Context, spaceID, filesystemID, snapshotID string, opts linodego.NFSSnapshotCloneOptions) (*linodego.NFSFilesystem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloneNFSSnapshot", ctx, spaceID, filesystemID, snapshotID, opts)
	ret0, _ := ret[0].(*linodego.NFSFilesystem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CloneNFSSnapshot indicates an expected call of CloneNFSSnapshot.
func (mr *MockLinodeClientMockRecorder) CloneNFSSnapshot(ctx, spaceID, filesystemID, snapshotID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloneNFSSnapshot", reflect.TypeOf((*MockLinodeClient)(nil).CloneNFSSnapshot), ctx, spaceID, filesystemID, snapshotID, opts)
}

// CreateNFSFilesystem mocks base method.
func (m *MockLinodeClient) CreateNFSFilesystem(ctx context.Context, spaceID string, opts linodego.NFSFilesystemCreateOptions) (*linodego.NFSFilesystem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNFSFilesystem", ctx, spaceID, opts)
	ret0, _ := ret[0].(*linodego.NFSFilesystem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNFSFilesystem indicates an expected call of CreateNFSFilesystem.
func (mr *MockLinodeClientMockRecorder) CreateNFSFilesystem(ctx, spaceID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNFSFilesystem", reflect.TypeOf((*MockLinodeClient)(nil).CreateNFSFilesystem), ctx, spaceID, opts)
}

// CreateNFSSnapshot mocks base method.
func (m *MockLinodeClient) CreateNFSSnapshot(ctx context.Context, spaceID, filesystemID string, opts linodego.NFSSnapshotCreateOptions) (*linodego.NFSSnapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNFSSnapshot", ctx, spaceID, filesystemID, opts)
	ret0, _ := ret[0].(*linodego.NFSSnapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNFSSnapshot indicates an expected call of CreateNFSSnapshot.
func (mr *MockLinodeClientMockRecorder) CreateNFSSnapshot(ctx, spaceID, filesystemID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNFSSnapshot", reflect.TypeOf((*MockLinodeClient)(nil).CreateNFSSnapshot), ctx, spaceID, filesystemID, opts)
}

// DeleteNFSFilesystem mocks base method.
func (m *MockLinodeClient) DeleteNFSFilesystem(ctx context.Context, spaceID, filesystemID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNFSFilesystem", ctx, spaceID, filesystemID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNFSFilesystem indicates an expected call of DeleteNFSFilesystem.
func (mr *MockLinodeClientMockRecorder) DeleteNFSFilesystem(ctx, spaceID, filesystemID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNFSFilesystem", reflect.TypeOf((*MockLinodeClient)(nil).DeleteNFSFilesystem), ctx, spaceID, filesystemID)
}

// DeleteNFSSnapshot mocks base method.
func (m *MockLinodeClient) DeleteNFSSnapshot(ctx context.Context, spaceID, filesystemID, snapshotID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNFSSnapshot", ctx, spaceID, filesystemID, snapshotID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNFSSnapshot indicates an expected call of DeleteNFSSnapshot.
func (mr *MockLinodeClientMockRecorder) DeleteNFSSnapshot(ctx, spaceID, filesystemID, snapshotID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNFSSnapshot", reflect.TypeOf((*MockLinodeClient)(nil).DeleteNFSSnapshot), ctx, spaceID, filesystemID, snapshotID)
}

// GetNFSFilesystem mocks base method.
func (m *MockLinodeClient) GetNFSFilesystem(ctx context.Context, spaceID, filesystemID string) (*linodego.NFSFilesystem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNFSFilesystem", ctx, spaceID, filesystemID)
	ret0, _ := ret[0].(*linodego.NFSFilesystem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNFSFilesystem indicates an expected call of GetNFSFilesystem.
func (mr *MockLinodeClientMockRecorder) GetNFSFilesystem(ctx, spaceID, filesystemID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNFSFilesystem", reflect.TypeOf((*MockLinodeClient)(nil).GetNFSFilesystem), ctx, spaceID, filesystemID)
}

// GetNFSFilesystemAccessPolicy mocks base method.
func (m *MockLinodeClient) GetNFSFilesystemAccessPolicy(ctx context.Context, spaceID, filesystemID string) (*linodego.NFSFilesystemAccessPolicy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNFSFilesystemAccessPolicy", ctx, spaceID, filesystemID)
	ret0, _ := ret[0].(*linodego.NFSFilesystemAccessPolicy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNFSFilesystemAccessPolicy indicates an expected call of GetNFSFilesystemAccessPolicy.
func (mr *MockLinodeClientMockRecorder) GetNFSFilesystemAccessPolicy(ctx, spaceID, filesystemID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNFSFilesystemAccessPolicy", reflect.TypeOf((*MockLinodeClient)(nil).GetNFSFilesystemAccessPolicy), ctx, spaceID, filesystemID)
}

// GetNFSFilesystemByID mocks base method.
func (m *MockLinodeClient) GetNFSFilesystemByID(ctx context.Context, filesystemID string) (*linodego.NFSFilesystem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNFSFilesystemByID", ctx, filesystemID)
	ret0, _ := ret[0].(*linodego.NFSFilesystem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNFSFilesystemByID indicates an expected call of GetNFSFilesystemByID.
func (mr *MockLinodeClientMockRecorder) GetNFSFilesystemByID(ctx, filesystemID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNFSFilesystemByID", reflect.TypeOf((*MockLinodeClient)(nil).GetNFSFilesystemByID), ctx, filesystemID)
}

// GetNFSSnapshot mocks base method.
func (m *MockLinodeClient) GetNFSSnapshot(ctx context.Context, spaceID, filesystemID, snapshotID string) (*linodego.NFSSnapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNFSSnapshot", ctx, spaceID, filesystemID, snapshotID)
	ret0, _ := ret[0].(*linodego.NFSSnapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNFSSnapshot indicates an expected call of GetNFSSnapshot.
func (mr *MockLinodeClientMockRecorder) GetNFSSnapshot(ctx, spaceID, filesystemID, snapshotID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNFSSnapshot", reflect.TypeOf((*MockLinodeClient)(nil).GetNFSSnapshot), ctx, spaceID, filesystemID, snapshotID)
}

// GetNFSSpace mocks base method.
func (m *MockLinodeClient) GetNFSSpace(ctx context.Context, spaceID string) (*linodego.NFSSpace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNFSSpace", ctx, spaceID)
	ret0, _ := ret[0].(*linodego.NFSSpace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNFSSpace indicates an expected call of GetNFSSpace.
func (mr *MockLinodeClientMockRecorder) GetNFSSpace(ctx, spaceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNFSSpace", reflect.TypeOf((*MockLinodeClient)(nil).GetNFSSpace), ctx, spaceID)
}

// GetNFSSpaceAccessPolicy mocks base method.
func (m *MockLinodeClient) GetNFSSpaceAccessPolicy(ctx context.Context, spaceID string) (*linodego.NFSSpaceAccessPolicy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNFSSpaceAccessPolicy", ctx, spaceID)
	ret0, _ := ret[0].(*linodego.NFSSpaceAccessPolicy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNFSSpaceAccessPolicy indicates an expected call of GetNFSSpaceAccessPolicy.
func (mr *MockLinodeClientMockRecorder) GetNFSSpaceAccessPolicy(ctx, spaceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNFSSpaceAccessPolicy", reflect.TypeOf((*MockLinodeClient)(nil).GetNFSSpaceAccessPolicy), ctx, spaceID)
}

// ListInterfaces mocks base method.
func (m *MockLinodeClient) ListInterfaces(ctx context.Context, linodeID int, opts *linodego.ListOptions) ([]linodego.LinodeInterface, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInterfaces", ctx, linodeID, opts)
	ret0, _ := ret[0].([]linodego.LinodeInterface)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInterfaces indicates an expected call of ListInterfaces.
func (mr *MockLinodeClientMockRecorder) ListInterfaces(ctx, linodeID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInterfaces", reflect.TypeOf((*MockLinodeClient)(nil).ListInterfaces), ctx, linodeID, opts)
}

// ListNFSFilesystems mocks base method.
func (m *MockLinodeClient) ListNFSFilesystems(ctx context.Context, spaceID string, opts *linodego.ListOptions) ([]linodego.NFSFilesystem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNFSFilesystems", ctx, spaceID, opts)
	ret0, _ := ret[0].([]linodego.NFSFilesystem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNFSFilesystems indicates an expected call of ListNFSFilesystems.
func (mr *MockLinodeClientMockRecorder) ListNFSFilesystems(ctx, spaceID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNFSFilesystems", reflect.TypeOf((*MockLinodeClient)(nil).ListNFSFilesystems), ctx, spaceID, opts)
}

// ListNFSSnapshots mocks base method.
func (m *MockLinodeClient) ListNFSSnapshots(ctx context.Context, spaceID, filesystemID string, opts *linodego.ListOptions) ([]linodego.NFSSnapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNFSSnapshots", ctx, spaceID, filesystemID, opts)
	ret0, _ := ret[0].([]linodego.NFSSnapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNFSSnapshots indicates an expected call of ListNFSSnapshots.
func (mr *MockLinodeClientMockRecorder) ListNFSSnapshots(ctx, spaceID, filesystemID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNFSSnapshots", reflect.TypeOf((*MockLinodeClient)(nil).ListNFSSnapshots), ctx, spaceID, filesystemID, opts)
}

// ListNFSSpaces mocks base method.
func (m *MockLinodeClient) ListNFSSpaces(ctx context.Context, opts *linodego.ListOptions) ([]linodego.NFSSpace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNFSSpaces", ctx, opts)
	ret0, _ := ret[0].([]linodego.NFSSpace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNFSSpaces indicates an expected call of ListNFSSpaces.
func (mr *MockLinodeClientMockRecorder) ListNFSSpaces(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNFSSpaces", reflect.TypeOf((*MockLinodeClient)(nil).ListNFSSpaces), ctx, opts)
}

// UpdateNFSFilesystemAccessPolicy mocks base method.
func (m *MockLinodeClient) UpdateNFSFilesystemAccessPolicy(ctx context.Context, spaceID, filesystemID string, opts linodego.NFSFilesystemAccessPolicyUpdateOptions) (*linodego.NFSFilesystemAccessPolicy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNFSFilesystemAccessPolicy", ctx, spaceID, filesystemID, opts)
	ret0, _ := ret[0].(*linodego.NFSFilesystemAccessPolicy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateNFSFilesystemAccessPolicy indicates an expected call of UpdateNFSFilesystemAccessPolicy.
func (mr *MockLinodeClientMockRecorder) UpdateNFSFilesystemAccessPolicy(ctx, spaceID, filesystemID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNFSFilesystemAccessPolicy", reflect.TypeOf((*MockLinodeClient)(nil).UpdateNFSFilesystemAccessPolicy), ctx, spaceID, filesystemID, opts)
}

// UpdateNFSSpaceAccessPolicy mocks base method.
func (m *MockLinodeClient) UpdateNFSSpaceAccessPolicy(ctx context.Context, spaceID string, opts linodego.NFSSpaceAccessPolicyUpdateOptions) (*linodego.NFSSpaceAccessPolicy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNFSSpaceAccessPolicy", ctx, spaceID, opts)
	ret0, _ := ret[0].(*linodego.NFSSpaceAccessPolicy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateNFSSpaceAccessPolicy indicates an expected call of UpdateNFSSpaceAccessPolicy.
func (mr *MockLinodeClientMockRecorder) UpdateNFSSpaceAccessPolicy(ctx, spaceID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNFSSpaceAccessPolicy", reflect.TypeOf((*MockLinodeClient)(nil).UpdateNFSSpaceAccessPolicy), ctx, spaceID, opts)
}
