// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/linode-client/client.go
//
// Generated by this command:
//
//	mockgen -source=pkg/linode-client/client.go -destination=mocks/mock_linodeclient.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	linodego "github.com/linode/linodego/v2"
	gomock "go.uber.org/mock/gomock"
)

// MockLinodeClient is a mock of LinodeClient interface.
type MockLinodeClient struct {
	ctrl     *gomock.Controller
	recorder *MockLinodeClientMockRecorder
	isgomock struct{}
}

// MockLinodeClientMockRecorder is the mock recorder for MockLinodeClient.
type MockLinodeClientMockRecorder struct {
	mock *MockLinodeClient
}

// NewMockLinodeClient creates a new mock instance.
func NewMockLinodeClient(ctrl *gomock.Controller) *MockLinodeClient {
	mock := &MockLinodeClient{ctrl: ctrl}
	mock.recorder = &MockLinodeClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinodeClient) EXPECT() *MockLinodeClientMockRecorder {
	return m.recorder
}

// CreateNFSFilesystem mocks base method.
func (m *MockLinodeClient) CreateNFSFilesystem(ctx context.Context, spaceID int, opts linodego.NFSFilesystemCreateOptions) (*linodego.NFSFilesystem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNFSFilesystem", ctx, spaceID, opts)
	ret0, _ := ret[0].(*linodego.NFSFilesystem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNFSFilesystem indicates an expected call of CreateNFSFilesystem.
func (mr *MockLinodeClientMockRecorder) CreateNFSFilesystem(ctx, spaceID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNFSFilesystem", reflect.TypeOf((*MockLinodeClient)(nil).CreateNFSFilesystem), ctx, spaceID, opts)
}

// DeleteNFSFilesystem mocks base method.
func (m *MockLinodeClient) DeleteNFSFilesystem(ctx context.Context, spaceID, filesystemID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNFSFilesystem", ctx, spaceID, filesystemID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNFSFilesystem indicates an expected call of DeleteNFSFilesystem.
func (mr *MockLinodeClientMockRecorder) DeleteNFSFilesystem(ctx, spaceID, filesystemID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNFSFilesystem", reflect.TypeOf((*MockLinodeClient)(nil).DeleteNFSFilesystem), ctx, spaceID, filesystemID)
}

// GetInstance mocks base method.
func (m *MockLinodeClient) GetInstance(ctx context.Context, linodeID int) (*linodego.Instance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInstance", ctx, linodeID)
	ret0, _ := ret[0].(*linodego.Instance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInstance indicates an expected call of GetInstance.
func (mr *MockLinodeClientMockRecorder) GetInstance(ctx, linodeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInstance", reflect.TypeOf((*MockLinodeClient)(nil).GetInstance), ctx, linodeID)
}

// GetNFSFilesystemAccessPolicy mocks base method.
func (m *MockLinodeClient) GetNFSFilesystemAccessPolicy(ctx context.Context, spaceID, filesystemID int) (*linodego.NFSFilesystemAccessPolicy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNFSFilesystemAccessPolicy", ctx, spaceID, filesystemID)
	ret0, _ := ret[0].(*linodego.NFSFilesystemAccessPolicy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNFSFilesystemAccessPolicy indicates an expected call of GetNFSFilesystemAccessPolicy.
func (mr *MockLinodeClientMockRecorder) GetNFSFilesystemAccessPolicy(ctx, spaceID, filesystemID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNFSFilesystemAccessPolicy", reflect.TypeOf((*MockLinodeClient)(nil).GetNFSFilesystemAccessPolicy), ctx, spaceID, filesystemID)
}

// GetNFSFilesystemInSpace mocks base method.
func (m *MockLinodeClient) GetNFSFilesystemInSpace(ctx context.Context, spaceID, filesystemID int) (*linodego.NFSFilesystem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNFSFilesystemInSpace", ctx, spaceID, filesystemID)
	ret0, _ := ret[0].(*linodego.NFSFilesystem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNFSFilesystemInSpace indicates an expected call of GetNFSFilesystemInSpace.
func (mr *MockLinodeClientMockRecorder) GetNFSFilesystemInSpace(ctx, spaceID, filesystemID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNFSFilesystemInSpace", reflect.TypeOf((*MockLinodeClient)(nil).GetNFSFilesystemInSpace), ctx, spaceID, filesystemID)
}

// GetNFSSpace mocks base method.
func (m *MockLinodeClient) GetNFSSpace(ctx context.Context, spaceID int) (*linodego.NFSSpace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNFSSpace", ctx, spaceID)
	ret0, _ := ret[0].(*linodego.NFSSpace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNFSSpace indicates an expected call of GetNFSSpace.
func (mr *MockLinodeClientMockRecorder) GetNFSSpace(ctx, spaceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNFSSpace", reflect.TypeOf((*MockLinodeClient)(nil).GetNFSSpace), ctx, spaceID)
}

// GetNFSSpaceAccessPolicy mocks base method.
func (m *MockLinodeClient) GetNFSSpaceAccessPolicy(ctx context.Context, spaceID int) (*linodego.NFSSpaceAccessPolicy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNFSSpaceAccessPolicy", ctx, spaceID)
	ret0, _ := ret[0].(*linodego.NFSSpaceAccessPolicy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNFSSpaceAccessPolicy indicates an expected call of GetNFSSpaceAccessPolicy.
func (mr *MockLinodeClientMockRecorder) GetNFSSpaceAccessPolicy(ctx, spaceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNFSSpaceAccessPolicy", reflect.TypeOf((*MockLinodeClient)(nil).GetNFSSpaceAccessPolicy), ctx, spaceID)
}

// ListInstanceConfigs mocks base method.
func (m *MockLinodeClient) ListInstanceConfigs(ctx context.Context, linodeID int, opts *linodego.ListOptions) ([]linodego.InstanceConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInstanceConfigs", ctx, linodeID, opts)
	ret0, _ := ret[0].([]linodego.InstanceConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInstanceConfigs indicates an expected call of ListInstanceConfigs.
func (mr *MockLinodeClientMockRecorder) ListInstanceConfigs(ctx, linodeID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInstanceConfigs", reflect.TypeOf((*MockLinodeClient)(nil).ListInstanceConfigs), ctx, linodeID, opts)
}

// ListInterfaces mocks base method.
func (m *MockLinodeClient) ListInterfaces(ctx context.Context, linodeID int, opts *linodego.ListOptions) ([]linodego.LinodeInterface, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInterfaces", ctx, linodeID, opts)
	ret0, _ := ret[0].([]linodego.LinodeInterface)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInterfaces indicates an expected call of ListInterfaces.
func (mr *MockLinodeClientMockRecorder) ListInterfaces(ctx, linodeID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInterfaces", reflect.TypeOf((*MockLinodeClient)(nil).ListInterfaces), ctx, linodeID, opts)
}

// ListNFSFilesystems mocks base method.
func (m *MockLinodeClient) ListNFSFilesystems(ctx context.Context, spaceID int, opts *linodego.ListOptions) ([]linodego.NFSFilesystem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNFSFilesystems", ctx, spaceID, opts)
	ret0, _ := ret[0].([]linodego.NFSFilesystem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNFSFilesystems indicates an expected call of ListNFSFilesystems.
func (mr *MockLinodeClientMockRecorder) ListNFSFilesystems(ctx, spaceID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNFSFilesystems", reflect.TypeOf((*MockLinodeClient)(nil).ListNFSFilesystems), ctx, spaceID, opts)
}

// ListNFSSpaces mocks base method.
func (m *MockLinodeClient) ListNFSSpaces(ctx context.Context, opts *linodego.ListOptions) ([]linodego.NFSSpace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNFSSpaces", ctx, opts)
	ret0, _ := ret[0].([]linodego.NFSSpace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNFSSpaces indicates an expected call of ListNFSSpaces.
func (mr *MockLinodeClientMockRecorder) ListNFSSpaces(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNFSSpaces", reflect.TypeOf((*MockLinodeClient)(nil).ListNFSSpaces), ctx, opts)
}

// UpdateNFSFilesystemAccessPolicy mocks base method.
func (m *MockLinodeClient) UpdateNFSFilesystemAccessPolicy(ctx context.Context, spaceID, filesystemID int, opts linodego.NFSFilesystemAccessPolicyUpdateOptions) (*linodego.NFSFilesystemAccessPolicy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNFSFilesystemAccessPolicy", ctx, spaceID, filesystemID, opts)
	ret0, _ := ret[0].(*linodego.NFSFilesystemAccessPolicy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateNFSFilesystemAccessPolicy indicates an expected call of UpdateNFSFilesystemAccessPolicy.
func (mr *MockLinodeClientMockRecorder) UpdateNFSFilesystemAccessPolicy(ctx, spaceID, filesystemID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNFSFilesystemAccessPolicy", reflect.TypeOf((*MockLinodeClient)(nil).UpdateNFSFilesystemAccessPolicy), ctx, spaceID, filesystemID, opts)
}

// UpdateNFSSpaceAccessPolicy mocks base method.
func (m *MockLinodeClient) UpdateNFSSpaceAccessPolicy(ctx context.Context, spaceID int, opts linodego.NFSSpaceAccessPolicyUpdateOptions) (*linodego.NFSSpaceAccessPolicy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNFSSpaceAccessPolicy", ctx, spaceID, opts)
	ret0, _ := ret[0].(*linodego.NFSSpaceAccessPolicy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateNFSSpaceAccessPolicy indicates an expected call of UpdateNFSSpaceAccessPolicy.
func (mr *MockLinodeClientMockRecorder) UpdateNFSSpaceAccessPolicy(ctx, spaceID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNFSSpaceAccessPolicy", reflect.TypeOf((*MockLinodeClient)(nil).UpdateNFSSpaceAccessPolicy), ctx, spaceID, opts)
}

// WaitForNFSFilesystemAccessPolicyStatus mocks base method.
func (m *MockLinodeClient) WaitForNFSFilesystemAccessPolicyStatus(ctx context.Context, spaceID, filesystemID int, status linodego.NFSAccessPolicyStatus) (*linodego.NFSFilesystemAccessPolicy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WaitForNFSFilesystemAccessPolicyStatus", ctx, spaceID, filesystemID, status)
	ret0, _ := ret[0].(*linodego.NFSFilesystemAccessPolicy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WaitForNFSFilesystemAccessPolicyStatus indicates an expected call of WaitForNFSFilesystemAccessPolicyStatus.
func (mr *MockLinodeClientMockRecorder) WaitForNFSFilesystemAccessPolicyStatus(ctx, spaceID, filesystemID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitForNFSFilesystemAccessPolicyStatus", reflect.TypeOf((*MockLinodeClient)(nil).WaitForNFSFilesystemAccessPolicyStatus), ctx, spaceID, filesystemID, status)
}

// WaitForNFSFilesystemStatus mocks base method.
func (m *MockLinodeClient) WaitForNFSFilesystemStatus(ctx context.Context, spaceID, filesystemID int, status linodego.NFSFilesystemStatus) (*linodego.NFSFilesystem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WaitForNFSFilesystemStatus", ctx, spaceID, filesystemID, status)
	ret0, _ := ret[0].(*linodego.NFSFilesystem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WaitForNFSFilesystemStatus indicates an expected call of WaitForNFSFilesystemStatus.
func (mr *MockLinodeClientMockRecorder) WaitForNFSFilesystemStatus(ctx, spaceID, filesystemID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitForNFSFilesystemStatus", reflect.TypeOf((*MockLinodeClient)(nil).WaitForNFSFilesystemStatus), ctx, spaceID, filesystemID, status)
}

// WaitForNFSSpaceAccessPolicyStatus mocks base method.
func (m *MockLinodeClient) WaitForNFSSpaceAccessPolicyStatus(ctx context.Context, spaceID int, status linodego.NFSAccessPolicyStatus) (*linodego.NFSSpaceAccessPolicy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WaitForNFSSpaceAccessPolicyStatus", ctx, spaceID, status)
	ret0, _ := ret[0].(*linodego.NFSSpaceAccessPolicy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WaitForNFSSpaceAccessPolicyStatus indicates an expected call of WaitForNFSSpaceAccessPolicyStatus.
func (mr *MockLinodeClientMockRecorder) WaitForNFSSpaceAccessPolicyStatus(ctx, spaceID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitForNFSSpaceAccessPolicyStatus", reflect.TypeOf((*MockLinodeClient)(nil).WaitForNFSSpaceAccessPolicyStatus), ctx, spaceID, status)
}
